version: 2.1
commands:
  my-command:
    steps:
      - run: echo "hello job"
      - run: python --version
jobs:
    my-job:
        docker:
            - image: circleci/python:3.9
        steps:
            - my-command
workflows:
    my-job-workflow:
        jobs:
          - my-job
