version: 2.1
parameters:
  my-message:
    type: string
    default: "hello by message"
commands:
  my-command:
    steps:
      - run: echo << pipeline.parameters.my-message >>
      - run: python --version
jobs:
    my-job:
        docker:
            - image: circleci/python:3.9
        steps:
            - my-command
workflows:
    my-job-workflow:
        jobs:
          - my-job
