version: 2.1
jobs:
    my-job:
        docker:
            - image: circleci/python:3.9
        steps:
            - run: echo "hello job"
            - run: python --version
workflows:
    my-job-workflow:
        jobs:
          - my-job
